version: "3.8"
name: webengineering-project
services:
  nodejs:
    image: definitelynotsimon13/webengineering:deploy
    environment:
      NODE_ENV: "production"

  nginx:
    image: definitelynotsimon13/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - nodejs
