services:
  nodejs:
    image: definitelynotsimon13/webengineering:latest
    container_name: nodejs_app
    environment:
      NODE_ENV: "production"


  nginx:
    image: definitelynotsimon13/nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - nodejs
